{
  lib,
  pkgs,
  config,
  ...
}:

with lib;
let
  cfg = config.local.sops;
in
{
  options.local.sops = {
    enable = mkEnableOption "sops";
    sopsFile = mkOption {
      type = types.path;
    };
    keyFile = mkOption {
      type = types.path;
    };
  };

  config = mkIf cfg.enable {
    sops.defaultSopsFile = cfg.sopsFile;
    sops.defaultSopsFormat = "yaml";
    # disable verifying encrypted sops files during nixos-rebuild
    sops.validateSopsFiles = false;

    # sops private key to decrypt secrets
    # generated by:
    # $ age-keygen -o ~/.config/sops/age/keys.txt
    # public key of the private age key (placed on top of sops file) can be found by:
    # $ age-keygen -y ~/.config/sops/age/keys.txt
    sops.age.keyFile = cfg.keyFile;

    # key attrs defined in sops file (secrets/secrets.yaml)
    # To edit secrets/secrets.yaml:
    # $ just shell sops
    # $ sops secrets/secrets.yaml
    # To access secrets: cat /run/secrets/myservice/my_subdir/my_secret
    # sops.secrets.example_key = { };
    # sops.secrets."myservice/my_subdir/my_secret" = {
    # # secrets owned by root by default, to change owner and group
    #   owner = config.users.users.<name>.name;
    #   group = config.users.groups.<name>.name;
    # };

    sops = {
      secrets = {
        email = { };
        "opnsense/url" = { };
        "opnsense/username" = { };
        "opnsense/password" = { };
      };
    };

    # example to make service access secret files
    # From https://github.com/vimjoyer/sops-nix-video
    # systemd.services."sometestservice" = {
    #   script = ''
    #     echo "
    #     Hey bro! I'm a service, and imma send this secure password:
    #     $(cat ${config.sops.secrets."myservice/my_subdir/my_secret".path})
    #     located in:
    #     ${config.sops.secrets."myservice/my_subdir/my_secret".path}
    #     to database and hack the mainframe
    #     " > /var/lib/sometestservice/testfile
    #   '';
    #   serviceConfig = {
    #     User = "sometestservice";
    #     WorkingDirectory = "/var/lib/sometestservice";
    #   };
    # };
    #
    # users.users.sometestservice = {
    #   home = "/var/lib/sometestservice";
    #   createHome = true;
    #   isSystemUser = true;
    #   group = "sometestservice";
    # };
    # users.groups.sometestservice = { };
  };
}
