# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    # "kvm-amd"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/51a20da4-9e2f-43ee-84f0-cbaf6553e170";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/51a20da4-9e2f-43ee-84f0-cbaf6553e170";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/51a20da4-9e2f-43ee-84f0-cbaf6553e170";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/24ED-A048";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # mergerfs setup
  # see https://trapexit.github.io/mergerfs/latest/quickstart/#configuration
  # maybe add snapraid later
  # https://discourse.nixos.org/t/feedback-and-advice-on-setting-up-mergerfs-snapraid-in-nixos/58290
  fileSystems."/mnt/disk/hdd/2T-WCC4M4VTXZ9Z" = {
    device = "/dev/disk/by-label/WCC4M4VTXZ9Z";
    fsType = "xfs";
  };
  fileSystems."/mnt/disk/hdd/2T-WCC4M4VTXD46" = {
    device = "/dev/disk/by-label/WCC4M4VTXD46";
    fsType = "xfs";
  };
  fileSystems."/data" = {
    depends = [
      "/mnt/disk/hdd/2T-WCC4M4VTXZ9Z"
      "/mnt/disk/hdd/2T-WCC4M4VTXD46"
    ];
    device = "/mnt/disk/hdd/*";
    fsType = "fuse.mergerfs";
    options = [
      "cache.files=off"
      "category.create=pfrd"
      "func.getattr=newest"
      "dropcacheonclose=false"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/adbf1481-c7d7-4e80-8716-d9f02fd6b29a"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # facter
  hardware.facter.reportPath = ./facter.json;
}
